<a href="https://colab.research.google.com/github/amittian/Data_Structures_Algorithms_Python/blob/main/Leetcode_Data_Structure_Algo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import array

In [3]:
import array

# Creating a 1D array of integers
my_array = array.array('i', [1, 2, 3, 4, 5])

# Accessing elements
print("1D Array:", my_array)
print("First element:", my_array[0])
print("Last element:", my_array[-1])

# Modifying an element
my_array[2] = 10
print("Modified Array:", my_array)

1D Array: array('i', [1, 2, 3, 4, 5])
First element: 1
Last element: 5
Modified Array: array('i', [1, 2, 10, 4, 5])


In [2]:
input_array = np.array([1,2,3] ,dtype=np.int64)

print(input_array)
print(input_array.shape)
print(input_array.dtype)

[1 2 3]
(3,)
int64


In [4]:
import numpy as np

# Creating a 1D array using NumPy
one_d_array = np.array([1, 2, 3, 4, 5])

# Accessing elements
print("1D NumPy Array:", one_d_array)
print("First element:", one_d_array[0])
print("Last element:", one_d_array[-1])


1D NumPy Array: [1 2 3 4 5]
First element: 1
Last element: 5


In [5]:
# Creating a 2D array (matrix) using NumPy
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing elements
print("2D NumPy Array (Matrix):\n", two_d_array)
print("Element at row 1, col 2:", two_d_array[0, 1])  # Element at (0, 1)


2D NumPy Array (Matrix):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, col 2: 2


In [6]:
import array

# Step 1: Create an array of integers
my_array = array.array('i', [1, 2, 3, 4, 5])
print("Original Array:", my_array)

# Step 2: Insert a new element at index 2 (third position)
my_array.insert(2, 10)  # Insert '10' at index 2

# Step 3: Display the updated array
print("Array after Insertion:", my_array)


Original Array: array('i', [1, 2, 3, 4, 5])
Array after Insertion: array('i', [1, 2, 10, 3, 4, 5])


**Time Complexity of Insertion**
Time complexity refers to how the time taken by an operation increases as the size of the array grows. Let's break it down in simple terms.

**Best Case (O(1)):** If we insert an element at the end of the array, it takes constant time because no shifting of elements is required. The array just adds the new element at the last position.

**Worst Case (O(n)):** If we insert an element at the beginning or middle of the array, the array needs to shift all the elements to the right to make room for the new element.

**For example,** in the case above, inserting 10 at index 2 means the elements 3, 4, 5 have to move one position to the right. If the array has n elements, this shifting operation takes O(n) time.

In [7]:
for i in range(len(my_array)):
    print(my_array[i])

1
2
10
3
4
5


In [8]:
for i in my_array:
    print(i)

1
2
10
3
4
5


In [9]:
my_array * 10


array('i', [1, 2, 10, 3, 4, 5, 1, 2, 10, 3, 4, 5, 1, 2, 10, 3, 4, 5, 1, 2, 10, 3, 4, 5, 1, 2, 10, 3, 4, 5, 1, 2, 10, 3, 4, 5, 1, 2, 10, 3, 4, 5, 1, 2, 10, 3, 4, 5, 1, 2, 10, 3, 4, 5, 1, 2, 10, 3, 4, 5])

In [10]:
import array

# 1. Array of Signed Integers (Positive and Negative Integers)
signed_int_array = array.array('i', [1, -2, 3, -4, 5])
print("Signed Integer Array:", signed_int_array)

# 2. Array of Unsigned Integers (Positive Integers Only)
unsigned_int_array = array.array('I', [1, 2, 3, 4, 5])
print("Unsigned Integer Array:", unsigned_int_array)

# Uncommenting the next line will raise an OverflowError since -1 is not allowed in unsigned arrays
# unsigned_int_array.append(-1)  # OverflowError

# 3. Array of Floats (Positive and Negative Floating-Point Numbers)
float_array = array.array('f', [1.1, -2.2, 3.3, -4.4, 5.5])
print("Float Array:", float_array)


Signed Integer Array: array('i', [1, -2, 3, -4, 5])
Unsigned Integer Array: array('I', [1, 2, 3, 4, 5])
Float Array: array('f', [1.100000023841858, -2.200000047683716, 3.299999952316284, -4.400000095367432, 5.5])


**📘 Further Notes: Time and Space Complexity**
**Time Complexity:**

Accessing elements in an array: O(1) (constant time).

Inserting an element at the end: O(1) (constant time).

Inserting an element at the beginning or middle: O(n) (linear time), because all elements must shift.

**Space Complexity:**

Arrays use a fixed amount of memory for each element, which is efficient when handling large numerical datasets.

Space complexity of insertion is O(1) because no extra space is needed beyond the new element being inserted.

In [12]:
class Solution(object):
    def removeDuplicates(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        unique_list = list(set(nums))

        print(unique_list)
       # out_list = []

        original_len = len(nums)
        sorted_array_len = len(unique_list)
        diff = original_len - sorted_array_len
        out_list = ['_'] * diff
        print(out_list)

        unique_list.extend(out_list)
        print(unique_list)



        print(f"{len(unique_list)}, nums = {unique_list}")

In [13]:
# Example usage
if __name__ == "__main__":
    nums = [0,0,1,1,1,2,2,3,3,4]

    solution = Solution()
    result = solution.removeDuplicates(nums)


[0, 1, 2, 3, 4]
['_', '_', '_', '_', '_']
[0, 1, 2, 3, 4, '_', '_', '_', '_', '_']
10, nums = [0, 1, 2, 3, 4, '_', '_', '_', '_', '_']


In [23]:
class Solution(object):
    def removeDuplicates(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        unique_list = list(set(nums))
        unique_list = [ int(x) for x in unique_list]
        original_len = len(nums)
        sorted_array_len = len(unique_list)
        diff = original_len - sorted_array_len
        out_list = ['_'] * diff



        unique_list.extend(out_list)

        k = len(unique_list)

        #return unique_list

        return print(f"{k}, nums = {unique_list}")

# Example usage
if __name__ == "__main__":
    nums = [0,0,1,1,1,2,2,3,3,4]

    solution = Solution()
    result = solution.removeDuplicates(nums)


10, nums = [0, 1, 2, 3, 4, '_', '_', '_', '_', '_']


In [5]:
def count_greater_elements(A):
    # Initialize the max_so_far with a very small number (or the first element)
    max_so_far = float('-inf')  # This will track the maximum value we've seen so far
    count = 0  # This will count the elements that are greater than all previous ones
    max_list = []
    # Traverse the array from left to right
    for num in A:
        # If the current element is greater than the max_so_far
        if num > max_so_far:
            max_so_far = num  # Update the max_so_far
          #  count += 1  # Increment the count because we found a new max
            max_list.append(num)


    return len(max_list) , max_list

# Example usage
if __name__ == "__main__":

  A = [3, 7, 8, 4, 5, 9, 2]
  result = count_greater_elements(A)
  print(result)  # Output should be 4, as the elements are [3, 7, 8, 9]


(4, [3, 7, 8, 9])


In [9]:
class MyPrinter:
    def main_m(self):

        user_input = input()



        # YOUR CODE GOES HERE
        # Please take input and print output to standard input/output (stdin/stdout)
        # E.g. 'input()/raw_input()' for input & 'print' for output

        print("Hello " +user_input)

if __name__ == '__main__':

    my_printer = MyPrinter()
    my_printer.main_m()
    #main()

debug_this_code
Hello debug_this_code


In [14]:
class MyCal:
    def main(self):
        A = int(input())
        B = int(input())
        # Print seven lines as described above
        sum_A_B = A + B
        sub_A_B = A - B
        pro_A_B = A * B
        i_div = A / B
        f_div = A // B
        r_div = A % B
        p_A_B = A**B
        print(sum_A_B, sub_A_B, pro_A_B, i_div, f_div, r_div, p_A_B)
        return sum_A_B, sub_A_B, pro_A_B, i_div, f_div, r_div, p_A_B

if __name__ == '__main__':


  my_cal = MyCal()
  my_cal.main()

4
2
6 2 8 2.0 2 0 16


In [15]:
def main():
    num = int(input())
    # YOUR CODE GOES HERE
    if num >= 90 :
        print("grade A.")
    elif num >= 80 :
        print("grade B.")

    elif num >= 70 :
        print("grade C.")

    elif num >= 60 :
        print("grade D.")

    elif num >= 50 :
        print("grade E.")
    else:
        print("grade F.")


    return 0

if __name__ == '__main__':
    main()

59
grade E.


In [18]:
def main():
    N = int(input())
    # YOUR CODE GOES HERE
    for num in range(N) :
        if num % 2 == 1 :

            print(num)
    return 0

if __name__ == '__main__':
    main()

10
1
3
5
7
9


In [ ]:
def main():
    N = int(input())  # Taking an integer input N

    # Loop through the numbers from 0 to N-1
    for num in range(N):
        # Check if the number is odd
        if num % 2 == 1:
            print(num)  # Print the odd number

    return 0  # Return 0 (optional, not required in Python)

if __name__ == '__main__':
    main()


In [19]:
def main():
    N = int(input())  # Taking an integer input N

    # Loop through the numbers from 0 to N (inclusive)
    for num in range(N + 1):  # Loop goes up to N now, not N-1
        # Check if the number is a multiple of both 3 and 5 (i.e., multiple of 15)
        if num % 15 == 0:
            print(num)  # Print the number if it's divisible by 15

    return 0  # Return 0 (optional, not required in Python)

if __name__ == '__main__':
    main()


15
0
15


In [22]:
def main():
    S = input()


    #Print length of the string S
    print(len(S))

    #Print the first occurence of the letter 'a' in S

    print(S.index("a"))

    #Note it is guaranteed that letter a is present in the string S

    #Print all the characters with even index in S

    for i in range(len(S)) :

        if i % 2 == 0 :
            print(S[i] , end = '')



if __name__ == '__main__':
    main()

Bangalore
9
1
Bnaoe