<a href="https://colab.research.google.com/github/amittian/Data_Structures_Algorithms_Python/blob/main/Leetcode_Data_Structure_Algo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import array

In [3]:
import array

# Creating a 1D array of integers
my_array = array.array('i', [1, 2, 3, 4, 5])

# Accessing elements
print("1D Array:", my_array)
print("First element:", my_array[0])
print("Last element:", my_array[-1])

# Modifying an element
my_array[2] = 10
print("Modified Array:", my_array)

1D Array: array('i', [1, 2, 3, 4, 5])
First element: 1
Last element: 5
Modified Array: array('i', [1, 2, 10, 4, 5])


In [2]:
input_array = np.array([1,2,3] ,dtype=np.int64)

print(input_array)
print(input_array.shape)
print(input_array.dtype)

[1 2 3]
(3,)
int64


In [4]:
import numpy as np

# Creating a 1D array using NumPy
one_d_array = np.array([1, 2, 3, 4, 5])

# Accessing elements
print("1D NumPy Array:", one_d_array)
print("First element:", one_d_array[0])
print("Last element:", one_d_array[-1])


1D NumPy Array: [1 2 3 4 5]
First element: 1
Last element: 5


In [5]:
# Creating a 2D array (matrix) using NumPy
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing elements
print("2D NumPy Array (Matrix):\n", two_d_array)
print("Element at row 1, col 2:", two_d_array[0, 1])  # Element at (0, 1)


2D NumPy Array (Matrix):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, col 2: 2


In [6]:
import array

# Step 1: Create an array of integers
my_array = array.array('i', [1, 2, 3, 4, 5])
print("Original Array:", my_array)

# Step 2: Insert a new element at index 2 (third position)
my_array.insert(2, 10)  # Insert '10' at index 2

# Step 3: Display the updated array
print("Array after Insertion:", my_array)


Original Array: array('i', [1, 2, 3, 4, 5])
Array after Insertion: array('i', [1, 2, 10, 3, 4, 5])


**Time Complexity of Insertion**
Time complexity refers to how the time taken by an operation increases as the size of the array grows. Let's break it down in simple terms.

**Best Case (O(1)):** If we insert an element at the end of the array, it takes constant time because no shifting of elements is required. The array just adds the new element at the last position.

**Worst Case (O(n)):** If we insert an element at the beginning or middle of the array, the array needs to shift all the elements to the right to make room for the new element.

**For example,** in the case above, inserting 10 at index 2 means the elements 3, 4, 5 have to move one position to the right. If the array has n elements, this shifting operation takes O(n) time.

In [7]:
for i in range(len(my_array)):
    print(my_array[i])

1
2
10
3
4
5


In [8]:
for i in my_array:
    print(i)

1
2
10
3
4
5


In [9]:
my_array * 10


array('i', [1, 2, 10, 3, 4, 5, 1, 2, 10, 3, 4, 5, 1, 2, 10, 3, 4, 5, 1, 2, 10, 3, 4, 5, 1, 2, 10, 3, 4, 5, 1, 2, 10, 3, 4, 5, 1, 2, 10, 3, 4, 5, 1, 2, 10, 3, 4, 5, 1, 2, 10, 3, 4, 5, 1, 2, 10, 3, 4, 5])

In [10]:
import array

# 1. Array of Signed Integers (Positive and Negative Integers)
signed_int_array = array.array('i', [1, -2, 3, -4, 5])
print("Signed Integer Array:", signed_int_array)

# 2. Array of Unsigned Integers (Positive Integers Only)
unsigned_int_array = array.array('I', [1, 2, 3, 4, 5])
print("Unsigned Integer Array:", unsigned_int_array)

# Uncommenting the next line will raise an OverflowError since -1 is not allowed in unsigned arrays
# unsigned_int_array.append(-1)  # OverflowError

# 3. Array of Floats (Positive and Negative Floating-Point Numbers)
float_array = array.array('f', [1.1, -2.2, 3.3, -4.4, 5.5])
print("Float Array:", float_array)


Signed Integer Array: array('i', [1, -2, 3, -4, 5])
Unsigned Integer Array: array('I', [1, 2, 3, 4, 5])
Float Array: array('f', [1.100000023841858, -2.200000047683716, 3.299999952316284, -4.400000095367432, 5.5])


**📘 Further Notes: Time and Space Complexity**
**Time Complexity:**

Accessing elements in an array: O(1) (constant time).

Inserting an element at the end: O(1) (constant time).

Inserting an element at the beginning or middle: O(n) (linear time), because all elements must shift.

**Space Complexity:**

Arrays use a fixed amount of memory for each element, which is efficient when handling large numerical datasets.

Space complexity of insertion is O(1) because no extra space is needed beyond the new element being inserted.